markdown: rdiscount
pygments: true
permalink: /posts/:title
rdiscount:
  extensions: [smart]

name: Sayali Lunkad
url: http://sayalilunkad.github.io
twitter: sayalilunkad
github: sayalilunkad
gravatar_url: https://s.gravatar.com/avatar/c508e8fdd68e1a8a5b92d71359e700c1?s=80

comment: true
